---
version: '3'

tasks:
  run: # название задачи для запуска
    desc: "Runs all '.go' files."
    cmds:
      - go run ./...
      
  test: # название задачи для запуска
    desc: "Runs all test files without cache and with info."
    cmds:
      - go test -v ./... -count=1
      
  d_build: # название задачи для запуска
    desc: "Build docker container."
    cmds:
      - docker build -t parcel_service .

  d_run: # название задачи для запуска
    desc: "Run container interactively."
    cmds:
      - docker run --name="parcel_app" -it parcel_service

  d_build_hub: # название задачи для запуска
    desc: "Build docker container from DockerHub."
    cmds:
      - docker pull --platform linux/x86_64 ra1nz0r/parcel_service

  d_run_hub: # название задачи для запуска
    desc: "Run container interactively downloaded from DokerHub."
    cmds:
      - docker run --name="parcel_app" -it --platform linux/x86_64 ra1nz0r/parcel_service